### ISSUE TITLE
Cannot "make"

### ISSUE THREAD

**Issue by Amusingdock25** [RichardHladik/outotune#2]
Hi, when I run "make" or "make install" in plugins/outotune/, after installing the dependencies and running both git submodule commands, I get the following as output:

Creating LV2 plugin library for outotune
/usr/bin/ld: cannot find -lworld: No such file or directory
collect2: error: ld returned 1 exit status
make: *** [../../dpf/Makefile.plugins.mk:218: ../../bin/outotune.lv2/outotune_dsp.so] Error 1

Running "locate libworld" doesn't return anything, if that's of any help.

I'm not sure if it's trying to access outotune/World or not, but either way I don't really know how to solve it. If this is an error on my end, please let me know and I'll remove the issue, but as of now I don't really know how to proceed. Thanks for your work!

**Comment by RichardHladik** [comment]
Hi, thanks for letting me know! This is apparently an error in the build process. Once I have time, I'll fix the `Makefile`, but for now, you can `make ../../World/build/libworld.a` from the `plugins/outotune/` directory, which should build the missing library. Running `make` after that should work.
